[WIP] GGML README
rustformers/llm pull request #224
Opened 2023-05-14 16:44 UTC by danforbes

2023-05-14 20:06 UTC, danforbes commented
I need help with (at least) vocabulary-scoring before this is ready to come out of draft.

2023-05-18 13:54 UTC, philpax commented
This is really well done! Awesome work, and sorry about not looking at it earlier!

Honestly, it's so thorough I'm wondering if I should encourage you to submit it to upstream GGML instead. They could certainly benefit from the documentation!

2023-05-19 21:54 UTC, philpax commented on crates/ggml/README.md
> +As described above, the model's [hyperparameters](#hyperparamaters) typically
#hyperparameters

2023-05-19 22:17 UTC, philpax requested changes
Alright, let's merge it here! Just a few small comments, but excellent work writing this up. It'll be a major help for both current and future contributors 🚀

2023-05-19 22:17 UTC, philpax commented on crates/ggml/README.md
> +[comment]: <> (I need help describing token-scoring)
I'd suggest linking to this: https://huggingface.co/learn/nlp-course/chapter6/5

but essentially, each token is given a score / probability, and the tokenization algorithm tries to select for tokens with the maximal probability.

2023-05-19 22:17 UTC, philpax commented on crates/ggml/README.md
> +language models (LLMs); the name is a portmanteau of the initials of its
Suggest mentioning that GGML is a library for ML stuff first, and then mention the format. The format can also be used for any ML thing that targets GGML-the-library (including whisper.cpp), not strictly LLMs, but that's where it's taken off.

2023-05-20 15:28 UTC, danforbes commented
Can you write one sentence that describes the purpose of token-scoring? Is this correct?

> Depending on the GGML version, the token may also include a 32-bit floating point score, which impacts how likely that token is to appear in text generated by the model.

2023-05-20 16:12 UTC, philpax commented
> Can you write one sentence that describes the purpose of token-scoring? Is this correct?
> 
> > Depending on the GGML version, the token may also include a 32-bit floating point score, which impacts how likely that token is to appear in text generated by the model.

I'd say more "how likely that token is to appear in the dataset that the model was trained on", but otherwise yeah that's fine

2023-05-20 17:04 UTC, philpax approved these changes

2023-05-20 17:08 UTC, danforbes commented
I'm ready for this to be merged if you are 👍🏻

2023-05-20 17:31 UTC, merged

2023-05-20 17:46 UTC, danforbes commented
> Honestly, it's so thorough I'm wondering if I should encourage you to submit it to upstream GGML instead. They could certainly benefit from the documentation!

Oh, that was always part of the plan 😉 https://github.com/ggerganov/ggml/pull/177